export const cityTownsMap = [
  {
    id: 1,
    name: 'Adana',
    towns: [
      { id: 1, name: 'Aladağ' },
      { id: 2, name: 'Ceyhan' },
      { id: 3, name: 'Çukurova' },
      { id: 4, name: 'Feke' },
      { id: 5, name: 'İmamoğlu' },
      { id: 6, name: 'Karaisalı' },
      { id: 7, name: 'Karataş' },
      { id: 8, name: 'Kozan' },
      { id: 9, name: 'Pozantı' },
      { id: 10, name: 'Saimbeyli' },
      { id: 11, name: 'Sarıçam' },
      { id: 12, name: 'Seyhan' },
      { id: 13, name: 'Tufanbeyli' },
      { id: 14, name: 'Yumurtalık' },
      { id: 15, name: 'Yüreğir' },
    ],
  },
  {
    id: 2,
    name: 'Ankara',
    towns: [
      { id: 1, name: 'Akyurt' },
      { id: 2, name: 'Altındağ' },
      { id: 3, name: 'Ayaş' },
      { id: 4, name: 'Bala' },
      { id: 5, name: 'Beypazarı' },
      { id: 6, name: 'Çamlıdere' },
      { id: 7, name: 'Çankaya' },
      { id: 8, name: 'Çubuk' },
      { id: 9, name: 'Elmadağ' },
      { id: 10, name: 'Etimesgut' },
      { id: 11, name: 'Evren' },
      { id: 12, name: 'Gölbaşı' },
      { id: 13, name: 'Güdül' },
      { id: 14, name: 'Haymana' },
      { id: 15, name: 'Kalecik' },
      { id: 16, name: 'Kahramankazan' },
      { id: 17, name: 'Keçiören' },
      { id: 18, name: 'Kızılcahamam' },
      { id: 19, name: 'Mamak' },
      { id: 20, name: 'Nallıhan' },
      { id: 21, name: 'Polatlı' },
      { id: 22, name: 'Pursaklar' },
      { id: 23, name: 'Sincan' },
      { id: 24, name: 'Şereflikoçhisar' },
      { id: 25, name: 'Yenimahalle' },
    ],
  },
  {
    id: 3,
    name: 'İstanbul',
    towns: [
      { id: 1, name: 'Adalar' },
      { id: 2, name: 'Arnavutköy' },
      { id: 3, name: 'Ataşehir' },
      { id: 4, name: 'Avcılar' },
      { id: 5, name: 'Bağcılar' },
      { id: 6, name: 'Bahçelievler' },
      { id: 7, name: 'Bakırköy' },
      { id: 8, name: 'Başakşehir' },
      { id: 9, name: 'Bayrampaşa' },
      { id: 10, name: 'Beşiktaş' },
      { id: 11, name: 'Beykoz' },
      { id: 12, name: 'Beylikdüzü' },
      { id: 13, name: 'Beyoğlu' },
      { id: 14, name: 'Büyükçekmece' },
      { id: 15, name: 'Çatalca' },
      { id: 16, name: 'Çekmeköy' },
      { id: 17, name: 'Esenler' },
      { id: 18, name: 'Esenyurt' },
      { id: 19, name: 'Eyüpsultan' },
      { id: 20, name: 'Fatih' },
      { id: 21, name: 'Gaziosmanpaşa' },
      { id: 22, name: 'Güngören' },
      { id: 23, name: 'Kadıköy' },
      { id: 24, name: 'Kağıthane' },
      { id: 25, name: 'Kartal' },
      { id: 26, name: 'Küçükçekmece' },
      { id: 27, name: 'Maltepe' },
      { id: 28, name: 'Pendik' },
      { id: 29, name: 'Sancaktepe' },
      { id: 30, name: 'Sarıyer' },
      { id: 31, name: 'Silivri' },
      { id: 32, name: 'Sultanbeyli' },
      { id: 33, name: 'Sultangazi' },
      { id: 34, name: 'Şile' },
      { id: 35, name: 'Şişli' },
      { id: 36, name: 'Tuzla' },
      { id: 37, name: 'Ümraniye' },
      { id: 38, name: 'Üsküdar' },
      { id: 39, name: 'Zeytinburnu' },
    ],
  },
  {
    id: 4,
    name: 'İzmir',
    towns: [
      { id: 1, name: 'Aliağa' },
      { id: 2, name: 'Balçova' },
      { id: 3, name: 'Bayındır' },
      { id: 4, name: 'Bayraklı' },
      { id: 5, name: 'Bergama' },
      { id: 6, name: 'Beydağ' },
      { id: 7, name: 'Bornova' },
      { id: 8, name: 'Buca' },
      { id: 9, name: 'Çeşme' },
      { id: 10, name: 'Çiğli' },
      { id: 11, name: 'Dikili' },
      { id: 12, name: 'Foça' },
      { id: 13, name: 'Gaziemir' },
      { id: 14, name: 'Güzelbahçe' },
      { id: 15, name: 'Karabağlar' },
      { id: 16, name: 'Karaburun' },
      { id: 17, name: 'Karşıyaka' },
      { id: 18, name: 'Kemalpaşa' },
      { id: 19, name: 'Kınık' },
      { id: 20, name: 'Kiraz' },
      { id: 21, name: 'Konak' },
      { id: 22, name: 'Menderes' },
      { id: 23, name: 'Menemen' },
      { id: 24, name: 'Narlıdere' },
      { id: 25, name: 'Ödemiş' },
      { id: 26, name: 'Seferihisar' },
      { id: 27, name: 'Selçuk' },
      { id: 28, name: 'Tire' },
      { id: 29, name: 'Torbalı' },
      { id: 30, name: 'Urla' },
    ],
  },
  {
    id: 5,
    name: 'Bursa',
    towns: [
      { id: 1, name: 'Büyükorhan' },
      { id: 2, name: 'Gemlik' },
      { id: 3, name: 'Gürsu' },
      { id: 4, name: 'Harmancık' },
      { id: 5, name: 'İnegöl' },
      { id: 6, name: 'İznik' },
      { id: 7, name: 'Karacabey' },
      { id: 8, name: 'Kestel' },
      { id: 9, name: 'Mudanya' },
      { id: 10, name: 'Mustafakemalpaşa' },
      { id: 11, name: 'Nilüfer' },
      { id: 12, name: 'Orhaneli' },
      { id: 13, name: 'Orhangazi' },
      { id: 14, name: 'Osmangazi' },
      { id: 15, name: 'Yenişehir' },
      { id: 16, name: 'Yıldırım' },
    ],
  },
  {
    id: 6,
    name: 'Antalya',
    towns: [
      { id: 1, name: 'Akseki' },
      { id: 2, name: 'Aksu' },
      { id: 3, name: 'Alanya' },
      { id: 4, name: 'Demre' },
      { id: 5, name: 'Döşemealtı' },
      { id: 6, name: 'Elmalı' },
      { id: 7, name: 'Finike' },
      { id: 8, name: 'Gazipaşa' },
      { id: 9, name: 'Gündoğmuş' },
      { id: 10, name: 'İbradı' },
      { id: 11, name: 'Kaş' },
      { id: 12, name: 'Kemer' },
      { id: 13, name: 'Kepez' },
      { id: 14, name: 'Konyaaltı' },
      { id: 15, name: 'Korkuteli' },
      { id: 16, name: 'Kumluca' },
      { id: 17, name: 'Manavgat' },
      { id: 18, name: 'Muratpaşa' },
      { id: 19, name: 'Serik' },
    ],
  },

  {
    id: 7,
    name: 'Eskişehir',
    towns: [
      { id: 1, name: 'Alpu' },
      { id: 2, name: 'Beylikova' },
      { id: 3, name: 'Çifteler' },
      { id: 4, name: 'Günyüzü' },
      { id: 5, name: 'Han' },
      { id: 6, name: 'İnönü' },
      { id: 7, name: 'Mahmudiye' },
      { id: 8, name: 'Mihalgazi' },
      { id: 9, name: 'Mihalıççık' },
      { id: 10, name: 'Odunpazarı' },
      { id: 11, name: 'Sarıcakaya' },
      { id: 12, name: 'Seyitgazi' },
      { id: 13, name: 'Sivrihisar' },
      { id: 14, name: 'Tepebaşı' },
    ],
  },
  {
    id: 8,
    name: 'Trabzon',
    towns: [
      { id: 1, name: 'Akçaabat' },
      { id: 2, name: 'Araklı' },
      { id: 3, name: 'Arsin' },
      { id: 4, name: 'Beşikdüzü' },
      { id: 5, name: 'Çarşıbaşı' },
      { id: 6, name: 'Çaykara' },
      { id: 7, name: 'Dernekpazarı' },
      { id: 8, name: 'Düzköy' },
      { id: 9, name: 'Hayrat' },
      { id: 10, name: 'Köprübaşı' },
      { id: 11, name: 'Maçka' },
      { id: 12, name: 'Of' },
      { id: 13, name: 'Ortahisar' },
      { id: 14, name: 'Sürmene' },
      { id: 15, name: 'Şalpazarı' },
      { id: 16, name: 'Tonya' },
      { id: 17, name: 'Vakfıkebir' },
      { id: 18, name: 'Yomra' },
    ],
  },
  {
    id: 9,
    name: 'Gaziantep',
    towns: [
      { id: 1, name: 'Araban' },
      { id: 2, name: 'İslahiye' },
      { id: 3, name: 'Karkamış' },
      { id: 4, name: 'Nizip' },
      { id: 5, name: 'Nurdağı' },
      { id: 6, name: 'Oğuzeli' },
      { id: 7, name: 'Şahinbey' },
      { id: 8, name: 'Şehitkamil' },
      { id: 9, name: 'Yavuzeli' },
    ],
  },
  {
    id: 10,
    name: 'Konya',
    towns: [
      { id: 1, name: 'Ahırlı' },
      { id: 2, name: 'Akören' },
      { id: 3, name: 'Akşehir' },
      { id: 4, name: 'Altınekin' },
      { id: 5, name: 'Beyşehir' },
      { id: 6, name: 'Bozkır' },
      { id: 7, name: 'Cihanbeyli' },
      { id: 8, name: 'Çeltik' },
      { id: 9, name: 'Çumra' },
      { id: 10, name: 'Derbent' },
      { id: 11, name: 'Derebucak' },
      { id: 12, name: 'Doğanhisar' },
      { id: 13, name: 'Emirgazi' },
      { id: 14, name: 'Ereğli' },
      { id: 15, name: 'Güneysınır' },
      { id: 16, name: 'Hadim' },
      { id: 17, name: 'Halkapınar' },
      { id: 18, name: 'Hüyük' },
      { id: 19, name: 'Ilgın' },
      { id: 20, name: 'Kadınhanı' },
      { id: 21, name: 'Karapınar' },
      { id: 22, name: 'Karatay' },
      { id: 23, name: 'Kulu' },
      { id: 24, name: 'Meram' },
      { id: 25, name: 'Sarayönü' },
      { id: 26, name: 'Selçuklu' },
      { id: 27, name: 'Seydişehir' },
      { id: 28, name: 'Taşkent' },
      { id: 29, name: 'Tuzlukçu' },
      { id: 30, name: 'Yalıhüyük' },
      { id: 31, name: 'Yunak' },
    ],
  },
  {
    id: 11,
    name: 'Mersin',
    towns: [
      { id: 1, name: 'Akdeniz' },
      { id: 2, name: 'Anamur' },
      { id: 3, name: 'Aydıncık' },
      { id: 4, name: 'Bozyazı' },
      { id: 5, name: 'Çamlıyayla' },
      { id: 6, name: 'Erdemli' },
      { id: 7, name: 'Gülnar' },
      { id: 8, name: 'Mezitli' },
      { id: 9, name: 'Mut' },
      { id: 10, name: 'Silifke' },
      { id: 11, name: 'Tarsus' },
      { id: 12, name: 'Toroslar' },
      { id: 13, name: 'Yenişehir' },
    ],
  },
  {
    id: 12,
    name: 'Samsun',
    towns: [
      { id: 1, name: 'Alaçam' },
      { id: 2, name: 'Asarcık' },
      { id: 3, name: 'Atakum' },
      { id: 4, name: 'Ayvacık' },
      { id: 5, name: 'Bafra' },
      { id: 6, name: 'Canik' },
      { id: 7, name: 'Çarşamba' },
      { id: 8, name: 'Havza' },
      { id: 9, name: 'İlkadım' },
      { id: 10, name: 'Kavak' },
      { id: 11, name: 'Ladik' },
      { id: 12, name: 'Ondokuzmayıs' },
      { id: 13, name: 'Salıpazarı' },
      { id: 14, name: 'Tekkeköy' },
      { id: 15, name: 'Terme' },
      { id: 16, name: 'Vezirköprü' },
      { id: 17, name: 'Yakakent' },
    ],
  },
  {
    id: 13,
    name: 'Diyarbakır',
    towns: [
      { id: 1, name: 'Bağlar' },
      { id: 2, name: 'Bismil' },
      { id: 3, name: 'Çermik' },
      { id: 4, name: 'Çınar' },
      { id: 5, name: 'Çüngüş' },
      { id: 6, name: 'Dicle' },
      { id: 7, name: 'Eğil' },
      { id: 8, name: 'Ergani' },
      { id: 9, name: 'Hani' },
      { id: 10, name: 'Hazro' },
      { id: 11, name: 'Kayapınar' },
      { id: 12, name: 'Kocaköy' },
      { id: 13, name: 'Kulp' },
      { id: 14, name: 'Lice' },
      { id: 15, name: 'Silvan' },
      { id: 16, name: 'Sur' },
      { id: 17, name: 'Yenişehir' },
    ],
  },
  {
    id: 14,
    name: 'Kayseri',
    towns: [
      { id: 1, name: 'Akkışla' },
      { id: 2, name: 'Bünyan' },
      { id: 3, name: 'Develi' },
      { id: 4, name: 'Felahiye' },
      { id: 5, name: 'Hacılar' },
      { id: 6, name: 'İncesu' },
      { id: 7, name: 'Kocasinan' },
      { id: 8, name: 'Melikgazi' },
      { id: 9, name: 'Özvatan' },
      { id: 10, name: 'Pınarbaşı' },
      { id: 11, name: 'Sarıoğlan' },
      { id: 12, name: 'Sarız' },
      { id: 13, name: 'Talas' },
      { id: 14, name: 'Tomarza' },
      { id: 15, name: 'Yahyalı' },
      { id: 16, name: 'Yeşilhisar' },
    ],
  },

  {
    id: 15,
    name: 'Erzurum',
    towns: [
      { id: 1, name: 'Aşkale' },
      { id: 2, name: 'Aziziye' },
      { id: 3, name: 'Çat' },
      { id: 4, name: 'Hınıs' },
      { id: 5, name: 'Horasan' },
      { id: 6, name: 'İspir' },
      { id: 7, name: 'Karaçoban' },
      { id: 8, name: 'Karayazı' },
      { id: 9, name: 'Köprüköy' },
      { id: 10, name: 'Narman' },
      { id: 11, name: 'Oltu' },
      { id: 12, name: 'Olur' },
      { id: 13, name: 'Palandöken' },
      { id: 14, name: 'Pasinler' },
      { id: 15, name: 'Pazaryolu' },
      { id: 16, name: 'Şenkaya' },
      { id: 17, name: 'Tekman' },
      { id: 18, name: 'Tortum' },
      { id: 19, name: 'Uzundere' },
      { id: 20, name: 'Yakutiye' },
    ],
  },
  {
    id: 16,
    name: 'Malatya',
    towns: [
      { id: 1, name: 'Akçadağ' },
      { id: 2, name: 'Arapgir' },
      { id: 3, name: 'Arguvan' },
      { id: 4, name: 'Battalgazi' },
      { id: 5, name: 'Darende' },
      { id: 6, name: 'Doğanşehir' },
      { id: 7, name: 'Doğanyol' },
      { id: 8, name: 'Hekimhan' },
      { id: 9, name: 'Kale' },
      { id: 10, name: 'Kuluncak' },
      { id: 11, name: 'Pütürge' },
      { id: 12, name: 'Yazıhan' },
      { id: 13, name: 'Yeşilyurt' },
    ],
  },
  {
    id: 17,
    name: 'Van',
    towns: [
      { id: 1, name: 'Bahçesaray' },
      { id: 2, name: 'Başkale' },
      { id: 3, name: 'Çaldıran' },
      { id: 4, name: 'Çatak' },
      { id: 5, name: 'Edremit' },
      { id: 6, name: 'Erciş' },
      { id: 7, name: 'Gevaş' },
      { id: 8, name: 'Gürpınar' },
      { id: 9, name: 'İpekyolu' },
      { id: 10, name: 'Muradiye' },
      { id: 11, name: 'Özalp' },
      { id: 12, name: 'Saray' },
      { id: 13, name: 'Tuşba' },
    ],
  },
  {
    id: 18,
    name: 'Muğla',
    towns: [
      { id: 1, name: 'Bodrum' },
      { id: 2, name: 'Dalaman' },
      { id: 3, name: 'Datça' },
      { id: 4, name: 'Fethiye' },
      { id: 5, name: 'Kavaklıdere' },
      { id: 6, name: 'Köyceğiz' },
      { id: 7, name: 'Marmaris' },
      { id: 8, name: 'Menteşe' },
      { id: 9, name: 'Milas' },
      { id: 10, name: 'Ortaca' },
      { id: 11, name: 'Seydikemer' },
      { id: 12, name: 'Ula' },
      { id: 13, name: 'Yatağan' },
    ],
  },
  {
    id: 19,
    name: 'Kocaeli',
    towns: [
      { id: 1, name: 'Başiskele' },
      { id: 2, name: 'Çayırova' },
      { id: 3, name: 'Darıca' },
      { id: 4, name: 'Derince' },
      { id: 5, name: 'Dilovası' },
      { id: 6, name: 'Gebze' },
      { id: 7, name: 'Gölcük' },
      { id: 8, name: 'İzmit' },
      { id: 9, name: 'Kandıra' },
      { id: 10, name: 'Karamürsel' },
      { id: 11, name: 'Kartepe' },
      { id: 12, name: 'Körfez' },
    ],
  },
  {
    id: 20,
    name: 'Manisa',
    towns: [
      { id: 1, name: 'Ahmetli' },
      { id: 2, name: 'Akhisar' },
      { id: 3, name: 'Alaşehir' },
      { id: 4, name: 'Demirci' },
      { id: 5, name: 'Gölmarmara' },
      { id: 6, name: 'Gördes' },
      { id: 7, name: 'Kırkağaç' },
      { id: 8, name: 'Köprübaşı' },
      { id: 9, name: 'Kula' },
      { id: 10, name: 'Salihli' },
      { id: 11, name: 'Sarıgöl' },
      { id: 12, name: 'Saruhanlı' },
      { id: 13, name: 'Selendi' },
      { id: 14, name: 'Soma' },
      { id: 15, name: 'Şehzadeler' },
      { id: 16, name: 'Turgutlu' },
      { id: 17, name: 'Yunusemre' },
    ],
  },
  {
    id: 21,
    name: 'Sakarya',
    towns: [
      { id: 1, name: 'Adapazarı' },
      { id: 2, name: 'Akyazı' },
      { id: 3, name: 'Arifiye' },
      { id: 4, name: 'Erenler' },
      { id: 5, name: 'Ferizli' },
      { id: 6, name: 'Geyve' },
      { id: 7, name: 'Hendek' },
      { id: 8, name: 'Karapürçek' },
      { id: 9, name: 'Karasu' },
      { id: 10, name: 'Kaynarca' },
      { id: 11, name: 'Kocaali' },
      { id: 12, name: 'Pamukova' },
      { id: 13, name: 'Sapanca' },
      { id: 14, name: 'Serdivan' },
      { id: 15, name: 'Söğütlü' },
      { id: 16, name: 'Taraklı' },
    ],
  },
  {
    id: 22,
    name: 'Balıkesir',
    towns: [
      { id: 1, name: 'Altıeylül' },
      { id: 2, name: 'Ayvalık' },
      { id: 3, name: 'Balya' },
      { id: 4, name: 'Bandırma' },
      { id: 5, name: 'Bigadiç' },
      { id: 6, name: 'Burhaniye' },
      { id: 7, name: 'Dursunbey' },
      { id: 8, name: 'Edremit' },
      { id: 9, name: 'Erdek' },
      { id: 10, name: 'Gömeç' },
      { id: 11, name: 'Gönen' },
      { id: 12, name: 'Havran' },
      { id: 13, name: 'İvrindi' },
      { id: 14, name: 'Karesi' },
      { id: 15, name: 'Kepsut' },
      { id: 16, name: 'Manyas' },
      { id: 17, name: 'Marmara' },
      { id: 18, name: 'Savaştepe' },
      { id: 19, name: 'Sındırgı' },
      { id: 20, name: 'Susurluk' },
    ],
  },

  {
    id: 23,
    name: 'Hatay',
    towns: [
      { id: 1, name: 'Altınözü' },
      { id: 2, name: 'Antakya' },
      { id: 3, name: 'Belen' },
      { id: 4, name: 'Defne' },
      { id: 5, name: 'Dörtyol' },
      { id: 6, name: 'Erzin' },
      { id: 7, name: 'Hassa' },
      { id: 8, name: 'İskenderun' },
      { id: 9, name: 'Kırıkhan' },
      { id: 10, name: 'Kumlu' },
      { id: 11, name: 'Payas' },
      { id: 12, name: 'Reyhanlı' },
      { id: 13, name: 'Samandağ' },
      { id: 14, name: 'Yayladağı' },
    ],
  },
  {
    id: 24,
    name: 'Kahramanmaraş',
    towns: [
      { id: 1, name: 'Afşin' },
      { id: 2, name: 'Andırın' },
      { id: 3, name: 'Çağlayancerit' },
      { id: 4, name: 'Dulkadiroğlu' },
      { id: 5, name: 'Ekinözü' },
      { id: 6, name: 'Elbistan' },
      { id: 7, name: 'Göksun' },
      { id: 8, name: 'Nurhak' },
      { id: 9, name: 'Onikişubat' },
      { id: 10, name: 'Pazarcık' },
      { id: 11, name: 'Türkoğlu' },
    ],
  },
  {
    id: 25,
    name: 'Aydın',
    towns: [
      { id: 1, name: 'Bozdoğan' },
      { id: 2, name: 'Buharkent' },
      { id: 3, name: 'Çine' },
      { id: 4, name: 'Didim' },
      { id: 5, name: 'Efeler' },
      { id: 6, name: 'Germencik' },
      { id: 7, name: 'İncirliova' },
      { id: 8, name: 'Karacasu' },
      { id: 9, name: 'Karpuzlu' },
      { id: 10, name: 'Koçarlı' },
      { id: 11, name: 'Köşk' },
      { id: 12, name: 'Kuşadası' },
      { id: 13, name: 'Kuyucak' },
      { id: 14, name: 'Nazilli' },
      { id: 15, name: 'Söke' },
      { id: 16, name: 'Sultanhisar' },
      { id: 17, name: 'Yenipazar' },
    ],
  },
  {
    id: 26,
    name: 'Tekirdağ',
    towns: [
      { id: 1, name: 'Çerkezköy' },
      { id: 2, name: 'Çorlu' },
      { id: 3, name: 'Ergene' },
      { id: 4, name: 'Hayrabolu' },
      { id: 5, name: 'Kapaklı' },
      { id: 6, name: 'Malkara' },
      { id: 7, name: 'Marmaraereğlisi' },
      { id: 8, name: 'Muratlı' },
      { id: 9, name: 'Saray' },
      { id: 10, name: 'Süleymanpaşa' },
      { id: 11, name: 'Şarköy' },
    ],
  },
  {
    id: 27,
    name: 'Edirne',
    towns: [
      { id: 1, name: 'Enez' },
      { id: 2, name: 'Havsa' },
      { id: 3, name: 'İpsala' },
      { id: 4, name: 'Keşan' },
      { id: 5, name: 'Lalapaşa' },
      { id: 6, name: 'Meriç' },
      { id: 7, name: 'Süloğlu' },
      { id: 8, name: 'Uzunköprü' },
    ],
  },
  {
    id: 28,
    name: 'Kırklareli',
    towns: [
      { id: 1, name: 'Babaeski' },
      { id: 2, name: 'Demirköy' },
      { id: 3, name: 'Kofçaz' },
      { id: 4, name: 'Lüleburgaz' },
      { id: 5, name: 'Pehlivanköy' },
      { id: 6, name: 'Pınarhisar' },
      { id: 7, name: 'Vize' },
    ],
  },
  {
    id: 29,
    name: 'Uşak',
    towns: [
      { id: 1, name: 'Banaz' },
      { id: 2, name: 'Eşme' },
      { id: 3, name: 'Karahallı' },
      { id: 4, name: 'Sivaslı' },
      { id: 5, name: 'Ulubey' },
      { id: 6, name: 'Merkez' },
    ],
  },
  {
    id: 30,
    name: 'Denizli',
    towns: [
      { id: 1, name: 'Acıpayam' },
      { id: 2, name: 'Babadağ' },
      { id: 3, name: 'Baklan' },
      { id: 4, name: 'Bekilli' },
      { id: 5, name: 'Beyağaç' },
      { id: 6, name: 'Bozkurt' },
      { id: 7, name: 'Buldan' },
      { id: 8, name: 'Çal' },
      { id: 9, name: 'Çameli' },
      { id: 10, name: 'Çardak' },
      { id: 11, name: 'Çivril' },
      { id: 12, name: 'Güney' },
      { id: 13, name: 'Honaz' },
      { id: 14, name: 'Kale' },
      { id: 15, name: 'Merkezefendi' },
      { id: 16, name: 'Pamukkale' },
      { id: 17, name: 'Sarayköy' },
      { id: 18, name: 'Serinhisar' },
      { id: 19, name: 'Tavas' },
    ],
  },

  {
    id: 31,
    name: 'Isparta',
    towns: [
      { id: 1, name: 'Aksu' },
      { id: 2, name: 'Atabey' },
      { id: 3, name: 'Eğirdir' },
      { id: 4, name: 'Gelendost' },
      { id: 5, name: 'Gönen' },
      { id: 6, name: 'Keçiborlu' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Senirkent' },
      { id: 9, name: 'Sütçüler' },
      { id: 10, name: 'Şarkikaraağaç' },
      { id: 11, name: 'Uluborlu' },
      { id: 12, name: 'Yalvaç' },
      { id: 13, name: 'Yenişarbademli' },
    ],
  },
  {
    id: 32,
    name: 'Zonguldak',
    towns: [
      { id: 1, name: 'Alaplı' },
      { id: 2, name: 'Çaycuma' },
      { id: 3, name: 'Devrek' },
      { id: 4, name: 'Ereğli' },
      { id: 5, name: 'Gökçebey' },
      { id: 6, name: 'Kilimli' },
      { id: 7, name: 'Kozlu' },
      { id: 8, name: 'Merkez' },
    ],
  },
  {
    id: 33,
    name: 'Karabük',
    towns: [
      { id: 1, name: 'Eflani' },
      { id: 2, name: 'Eskipazar' },
      { id: 3, name: 'Merkez' },
      { id: 4, name: 'Ovacık' },
      { id: 5, name: 'Safranbolu' },
      { id: 6, name: 'Yenice' },
    ],
  },
  {
    id: 34,
    name: 'Bartın',
    towns: [
      { id: 1, name: 'Amasra' },
      { id: 2, name: 'Kurucaşile' },
      { id: 3, name: 'Merkez' },
      { id: 4, name: 'Ulus' },
    ],
  },
  {
    id: 35,
    name: 'Kastamonu',
    towns: [
      { id: 1, name: 'Abana' },
      { id: 2, name: 'Ağlı' },
      { id: 3, name: 'Araç' },
      { id: 4, name: 'Azdavay' },
      { id: 5, name: 'Bozkurt' },
      { id: 6, name: 'Cide' },
      { id: 7, name: 'Çatalzeytin' },
      { id: 8, name: 'Daday' },
      { id: 9, name: 'Devrekani' },
      { id: 10, name: 'Doğanyurt' },
      { id: 11, name: 'Hanönü' },
      { id: 12, name: 'İhsangazi' },
      { id: 13, name: 'İnebolu' },
      { id: 14, name: 'Küre' },
      { id: 15, name: 'Merkez' },
      { id: 16, name: 'Pınarbaşı' },
      { id: 17, name: 'Şenpazar' },
      { id: 18, name: 'Seydiler' },
      { id: 19, name: 'Taşköprü' },
      { id: 20, name: 'Tosya' },
    ],
  },
  {
    id: 36,
    name: 'Sinop',
    towns: [
      { id: 1, name: 'Ayancık' },
      { id: 2, name: 'Boyabat' },
      { id: 3, name: 'Dikmen' },
      { id: 4, name: 'Durağan' },
      { id: 5, name: 'Erfelek' },
      { id: 6, name: 'Gerze' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Saraydüzü' },
      { id: 9, name: 'Türkeli' },
    ],
  },
  {
    id: 37,
    name: 'Çorum',
    towns: [
      { id: 1, name: 'Alaca' },
      { id: 2, name: 'Bayat' },
      { id: 3, name: 'Boğazkalan' },
      { id: 4, name: 'Dodurga' },
      { id: 5, name: 'İskilip' },
      { id: 6, name: 'Kargı' },
      { id: 7, name: 'Laçin' },
      { id: 8, name: 'Mecitözü' },
      { id: 9, name: 'Merkez' },
      { id: 10, name: 'Oğuzlar' },
      { id: 11, name: 'Ortaköy' },
      { id: 12, name: 'Osmancık' },
      { id: 13, name: 'Sungurlu' },
      { id: 14, name: 'Uğurludağ' },
    ],
  },
  {
    id: 38,
    name: 'Amasya',
    towns: [
      { id: 1, name: 'Göynücek' },
      { id: 2, name: 'Gümüşhacıköy' },
      { id: 3, name: 'Hamamözü' },
      { id: 4, name: 'Merkez' },
      { id: 5, name: 'Merzifon' },
      { id: 6, name: 'Suluova' },
      { id: 7, name: 'Taşova' },
    ],
  },
  {
    id: 39,
    name: 'Tokat',
    towns: [
      { id: 1, name: 'Almus' },
      { id: 2, name: 'Artova' },
      { id: 3, name: 'Başçiftlik' },
      { id: 4, name: 'Erbaa' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Niksar' },
      { id: 7, name: 'Pazar' },
      { id: 8, name: 'Reşadiye' },
      { id: 9, name: 'Sulusaray' },
      { id: 10, name: 'Turhal' },
      { id: 11, name: 'Yeşilyurt' },
      { id: 12, name: 'Zile' },
    ],
  },
  {
    id: 40,
    name: 'Yozgat',
    towns: [
      { id: 1, name: 'Akdağmadeni' },
      { id: 2, name: 'Aydıncık' },
      { id: 3, name: 'Boğazlıyan' },
      { id: 4, name: 'Çandır' },
      { id: 5, name: 'Çayıralan' },
      { id: 6, name: 'Çekerek' },
      { id: 7, name: 'Kadışehri' },
      { id: 8, name: 'Merkez' },
      { id: 9, name: 'Saraykent' },
      { id: 10, name: 'Sarıkaya' },
      { id: 11, name: 'Sorgun' },
      { id: 12, name: 'Şefaatli' },
      { id: 13, name: 'Yenifakılı' },
      { id: 14, name: 'Yerköy' },
    ],
  },
  {
    id: 41,
    name: 'Nevşehir',
    towns: [
      { id: 1, name: 'Acıgöl' },
      { id: 2, name: 'Avanos' },
      { id: 3, name: 'Derinkuyu' },
      { id: 4, name: 'Gülşehir' },
      { id: 5, name: 'Hacıbektaş' },
      { id: 6, name: 'Kozaklı' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Ürgüp' },
    ],
  },
  {
    id: 42,
    name: 'Niğde',
    towns: [
      { id: 1, name: 'Altunhisar' },
      { id: 2, name: 'Bor' },
      { id: 3, name: 'Çamardı' },
      { id: 4, name: 'Çiftlik' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Ulukışla' },
    ],
  },
  {
    id: 43,
    name: 'Giresun',
    towns: [
      { id: 1, name: 'Alucra' },
      { id: 2, name: 'Bulancak' },
      { id: 3, name: 'Çamoluk' },
      { id: 4, name: 'Çanakçı' },
      { id: 5, name: 'Dereli' },
      { id: 6, name: 'Doğankent' },
      { id: 7, name: 'Espiye' },
      { id: 8, name: 'Eynesil' },
      { id: 9, name: 'Görele' },
      { id: 10, name: 'Güce' },
      { id: 11, name: 'Keşap' },
      { id: 12, name: 'Merkez' },
      { id: 13, name: 'Piraziz' },
      { id: 14, name: 'Şebinkarahisar' },
      { id: 15, name: 'Tirebolu' },
      { id: 16, name: 'Yağlıdere' },
    ],
  },
  {
    id: 44,
    name: 'Rize',
    towns: [
      { id: 1, name: 'Ardeşen' },
      { id: 2, name: 'Çamlıhemşin' },
      { id: 3, name: 'Çayeli' },
      { id: 4, name: 'Derepazarı' },
      { id: 5, name: 'Fındıklı' },
      { id: 6, name: 'Güneysu' },
      { id: 7, name: 'Hemşin' },
      { id: 8, name: 'İkizdere' },
      { id: 9, name: 'İyidere' },
      { id: 10, name: 'Kalkandere' },
      { id: 11, name: 'Merkez' },
      { id: 12, name: 'Pazar' },
    ],
  },
  {
    id: 45,
    name: 'Artvin',
    towns: [
      { id: 1, name: 'Ardanuç' },
      { id: 2, name: 'Arhavi' },
      { id: 3, name: 'Borçka' },
      { id: 4, name: 'Hopa' },
      { id: 5, name: 'Kemalpaşa' },
      { id: 6, name: 'Merkez' },
      { id: 7, name: 'Murgul' },
      { id: 8, name: 'Şavşat' },
      { id: 9, name: 'Yusufeli' },
    ],
  },
  {
    id: 46,
    name: 'Ağrı',
    towns: [
      { id: 1, name: 'Diyadin' },
      { id: 2, name: 'Doğubayazıt' },
      { id: 3, name: 'Eleşkirt' },
      { id: 4, name: 'Hamur' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Patnos' },
      { id: 7, name: 'Taşlıçay' },
      { id: 8, name: 'Tutak' },
    ],
  },
  {
    id: 47,
    name: 'Ardahan',
    towns: [
      { id: 1, name: 'Çıldır' },
      { id: 2, name: 'Damal' },
      { id: 3, name: 'Göle' },
      { id: 4, name: 'Hanak' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Posof' },
    ],
  },
  {
    id: 48,
    name: 'Iğdır',
    towns: [
      { id: 1, name: 'Aralık' },
      { id: 2, name: 'Karakoyunlu' },
      { id: 3, name: 'Merkez' },
      { id: 4, name: 'Tuzluca' },
    ],
  },
  {
    id: 49,
    name: 'Tunceli',
    towns: [
      { id: 1, name: 'Çemişgezek' },
      { id: 2, name: 'Hozat' },
      { id: 3, name: 'Mazgirt' },
      { id: 4, name: 'Merkez' },
      { id: 5, name: 'Nazımiye' },
      { id: 6, name: 'Ovacık' },
      { id: 7, name: 'Pertek' },
      { id: 8, name: 'Pülümür' },
    ],
  },
  {
    id: 50,
    name: 'Elazığ',
    towns: [
      { id: 1, name: 'Ağın' },
      { id: 2, name: 'Alacakaya' },
      { id: 3, name: 'Arıcak' },
      { id: 4, name: 'Baskil' },
      { id: 5, name: 'Karakoçan' },
      { id: 6, name: 'Keban' },
      { id: 7, name: 'Kovancılar' },
      { id: 8, name: 'Maden' },
      { id: 9, name: 'Merkez' },
      { id: 10, name: 'Palu' },
      { id: 11, name: 'Sivrice' },
    ],
  },
  {
    id: 51,
    name: 'Bingöl',
    towns: [
      { id: 1, name: 'Adaklı' },
      { id: 2, name: 'Genç' },
      { id: 3, name: 'Karlıova' },
      { id: 4, name: 'Kiğı' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Solhan' },
      { id: 7, name: 'Yayladere' },
      { id: 8, name: 'Yedisu' },
    ],
  },
  {
    id: 52,
    name: 'Muş',
    towns: [
      { id: 1, name: 'Bulanık' },
      { id: 2, name: 'Hasköy' },
      { id: 3, name: 'Korkut' },
      { id: 4, name: 'Malazgirt' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Varto' },
    ],
  },
  {
    id: 53,
    name: 'Bitlis',
    towns: [
      { id: 1, name: 'Adilcevaz' },
      { id: 2, name: 'Ahlat' },
      { id: 3, name: 'Güroymak' },
      { id: 4, name: 'Hizan' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Mutki' },
      { id: 7, name: 'Tatvan' },
    ],
  },
  {
    id: 54,
    name: 'Hakkari',
    towns: [
      { id: 1, name: 'Çukurca' },
      { id: 2, name: 'Merkez' },
      { id: 3, name: 'Şemdinli' },
      { id: 4, name: 'Yüksekova' },
    ],
  },
  {
    id: 55,
    name: 'Şırnak',
    towns: [
      { id: 1, name: 'Beytüşşebap' },
      { id: 2, name: 'Cizre' },
      { id: 3, name: 'Güçlükonak' },
      { id: 4, name: 'İdil' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Silopi' },
      { id: 7, name: 'Uludere' },
    ],
  },
  {
    id: 56,
    name: 'Batman',
    towns: [
      { id: 1, name: 'Beşiri' },
      { id: 2, name: 'Gercüş' },
      { id: 3, name: 'Hasankeyf' },
      { id: 4, name: 'Kozluk' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Sason' },
    ],
  },
  {
    id: 57,
    name: 'Siirt',
    towns: [
      { id: 1, name: 'Baykan' },
      { id: 2, name: 'Eruh' },
      { id: 3, name: 'Kurtalan' },
      { id: 4, name: 'Merkez' },
      { id: 5, name: 'Pervari' },
      { id: 6, name: 'Şirvan' },
      { id: 7, name: 'Tillo' },
    ],
  },
  {
    id: 58,
    name: 'Şanlıurfa',
    towns: [
      { id: 1, name: 'Akçakale' },
      { id: 2, name: 'Birecik' },
      { id: 3, name: 'Bozova' },
      { id: 4, name: 'Ceylanpınar' },
      { id: 5, name: 'Eyyübiye' },
      { id: 6, name: 'Halfeti' },
      { id: 7, name: 'Haliliye' },
      { id: 8, name: 'Harran' },
      { id: 9, name: 'Hilvan' },
      { id: 10, name: 'Karaköprü' },
      { id: 11, name: 'Siverek' },
      { id: 12, name: 'Suruç' },
      { id: 13, name: 'Viranşehir' },
    ],
  },
  {
    id: 59,
    name: 'Mardin',
    towns: [
      { id: 1, name: 'Artuklu' },
      { id: 2, name: 'Dargeçit' },
      { id: 3, name: 'Derik' },
      { id: 4, name: 'Kızıltepe' },
      { id: 5, name: 'Mazıdağı' },
      { id: 6, name: 'Midyat' },
      { id: 7, name: 'Nusaybin' },
      { id: 8, name: 'Ömerli' },
      { id: 9, name: 'Savur' },
      { id: 10, name: 'Yeşilli' },
    ],
  },
  {
    id: 60,
    name: 'Kırıkkale',
    towns: [
      { id: 1, name: 'Bahşili' },
      { id: 2, name: 'Balışeyh' },
      { id: 3, name: 'Çelebi' },
      { id: 4, name: 'Delice' },
      { id: 5, name: 'Karakeçili' },
      { id: 6, name: 'Keskin' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Sulakyurt' },
      { id: 9, name: 'Yahşihan' },
    ],
  },
  {
    id: 61,
    name: 'Kırşehir',
    towns: [
      { id: 1, name: 'Akçakent' },
      { id: 2, name: 'Akpınar' },
      { id: 3, name: 'Boztepe' },
      { id: 4, name: 'Çiçekdağı' },
      { id: 5, name: 'Kaman' },
      { id: 6, name: 'Merkez' },
      { id: 7, name: 'Mucur' },
    ],
  },
  {
    id: 62,
    name: 'Nevşehir',
    towns: [
      { id: 1, name: 'Acıgöl' },
      { id: 2, name: 'Avanos' },
      { id: 3, name: 'Derinkuyu' },
      { id: 4, name: 'Gülşehir' },
      { id: 5, name: 'Hacıbektaş' },
      { id: 6, name: 'Kozaklı' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Ürgüp' },
    ],
  },
  {
    id: 63,
    name: 'Niğde',
    towns: [
      { id: 1, name: 'Altunhisar' },
      { id: 2, name: 'Bor' },
      { id: 3, name: 'Çamardı' },
      { id: 4, name: 'Çiftlik' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Ulukışla' },
    ],
  },
  {
    id: 64,
    name: 'Gümüşhane',
    towns: [
      { id: 1, name: 'Kelkit' },
      { id: 2, name: 'Köse' },
      { id: 3, name: 'Kürtün' },
      { id: 4, name: 'Merkez' },
      { id: 5, name: 'Şiran' },
      { id: 6, name: 'Torul' },
    ],
  },
  {
    id: 65,
    name: 'Bayburt',
    towns: [
      { id: 1, name: 'Aydıntepe' },
      { id: 2, name: 'Demirözü' },
      { id: 3, name: 'Merkez' },
    ],
  },
  {
    id: 66,
    name: 'Karaman',
    towns: [
      { id: 1, name: 'Ayrancı' },
      { id: 2, name: 'Başyayla' },
      { id: 3, name: 'Ermenek' },
      { id: 4, name: 'Kazımkarabekir' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Sarıveliler' },
    ],
  },
  {
    id: 67,
    name: 'Kilis',
    towns: [
      { id: 1, name: 'Elbeyli' },
      { id: 2, name: 'Merkez' },
      { id: 3, name: 'Musabeyli' },
      { id: 4, name: 'Polateli' },
    ],
  },
  {
    id: 68,
    name: 'Osmaniye',
    towns: [
      { id: 1, name: 'Bahçe' },
      { id: 2, name: 'Düziçi' },
      { id: 3, name: 'Hasanbeyli' },
      { id: 4, name: 'Kadirli' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Sumbas' },
      { id: 7, name: 'Toprakkale' },
    ],
  },
  {
    id: 69,
    name: 'Düzce',
    towns: [
      { id: 1, name: 'Akçakoca' },
      { id: 2, name: 'Cumayeri' },
      { id: 3, name: 'Çilimli' },
      { id: 4, name: 'Gölyaka' },
      { id: 5, name: 'Gümüşova' },
      { id: 6, name: 'Kaynaşlı' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Yığılca' },
    ],
  },
  {
    id: 70,
    name: 'Kırıkkale',
    towns: [
      { id: 1, name: 'Bahşili' },
      { id: 2, name: 'Balışeyh' },
      { id: 3, name: 'Çelebi' },
      { id: 4, name: 'Delice' },
      { id: 5, name: 'Karakeçili' },
      { id: 6, name: 'Keskin' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Sulakyurt' },
      { id: 9, name: 'Yahşihan' },
    ],
  },
  {
    id: 71,
    name: 'Kırşehir',
    towns: [
      { id: 1, name: 'Akçakent' },
      { id: 2, name: 'Akpınar' },
      { id: 3, name: 'Boztepe' },
      { id: 4, name: 'Çiçekdağı' },
      { id: 5, name: 'Kaman' },
      { id: 6, name: 'Merkez' },
      { id: 7, name: 'Mucur' },
    ],
  },
  {
    id: 72,
    name: 'Nevşehir',
    towns: [
      { id: 1, name: 'Acıgöl' },
      { id: 2, name: 'Avanos' },
      { id: 3, name: 'Derinkuyu' },
      { id: 4, name: 'Gülşehir' },
      { id: 5, name: 'Hacıbektaş' },
      { id: 6, name: 'Kozaklı' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Ürgüp' },
    ],
  },
  {
    id: 73,
    name: 'Niğde',
    towns: [
      { id: 1, name: 'Altunhisar' },
      { id: 2, name: 'Bor' },
      { id: 3, name: 'Çamardı' },
      { id: 4, name: 'Çiftlik' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Ulukışla' },
    ],
  },
  {
    id: 74,
    name: 'Gümüşhane',
    towns: [
      { id: 1, name: 'Kelkit' },
      { id: 2, name: 'Köse' },
      { id: 3, name: 'Kürtün' },
      { id: 4, name: 'Merkez' },
      { id: 5, name: 'Şiran' },
      { id: 6, name: 'Torul' },
    ],
  },
  {
    id: 75,
    name: 'Bayburt',
    towns: [
      { id: 1, name: 'Aydıntepe' },
      { id: 2, name: 'Demirözü' },
      { id: 3, name: 'Merkez' },
    ],
  },
  {
    id: 76,
    name: 'Karaman',
    towns: [
      { id: 1, name: 'Ayrancı' },
      { id: 2, name: 'Başyayla' },
      { id: 3, name: 'Ermenek' },
      { id: 4, name: 'Kazımkarabekir' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Sarıveliler' },
    ],
  },
  {
    id: 77,
    name: 'Kilis',
    towns: [
      { id: 1, name: 'Elbeyli' },
      { id: 2, name: 'Merkez' },
      { id: 3, name: 'Musabeyli' },
      { id: 4, name: 'Polateli' },
    ],
  },
  {
    id: 78,
    name: 'Osmaniye',
    towns: [
      { id: 1, name: 'Bahçe' },
      { id: 2, name: 'Düziçi' },
      { id: 3, name: 'Hasanbeyli' },
      { id: 4, name: 'Kadirli' },
      { id: 5, name: 'Merkez' },
      { id: 6, name: 'Sumbas' },
      { id: 7, name: 'Toprakkale' },
    ],
  },
  {
    id: 79,
    name: 'Düzce',
    towns: [
      { id: 1, name: 'Akçakoca' },
      { id: 2, name: 'Cumayeri' },
      { id: 3, name: 'Çilimli' },
      { id: 4, name: 'Gölyaka' },
      { id: 5, name: 'Gümüşova' },
      { id: 6, name: 'Kaynaşlı' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Yığılca' },
    ],
  },
  {
    id: 80,
    name: 'Kırıkkale',
    towns: [
      { id: 1, name: 'Bahşili' },
      { id: 2, name: 'Balışeyh' },
      { id: 3, name: 'Çelebi' },
      { id: 4, name: 'Delice' },
      { id: 5, name: 'Karakeçili' },
      { id: 6, name: 'Keskin' },
      { id: 7, name: 'Merkez' },
      { id: 8, name: 'Sulakyurt' },
      { id: 9, name: 'Yahşihan' },
    ],
  },
  {
    id: 81,
    name: 'Kırşehir',
    towns: [
      { id: 1, name: 'Akçakent' },
      { id: 2, name: 'Akpınar' },
      { id: 3, name: 'Boztepe' },
      { id: 4, name: 'Çiçekdağı' },
      { id: 5, name: 'Kaman' },
      { id: 6, name: 'Merkez' },
      { id: 7, name: 'Mucur' },
    ],
  },
];
